const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding grant opportunities...');

  // Clean existing grants first
  await prisma.grant.deleteMany();

  const grants = [
    // --- EDUCATION ---
    {
      name: "Smart School Digital Classroom Grant",
      provider: "Tech Mahindra Foundation (CSR)",
      type: "CSR",
      sector: "Education",
      state: "Telangana",
      minimumFunding: 500000,
      maximumFunding: 2000000,
      deadline: "2026-10-15",
      eligibility: "Registered NGOs operating in Telangana with at least 3 years of school partnership experience.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Annual Activity Report",
      description: "Supports upgrading infrastructure in rural and semi-urban government schools to establish digital classrooms and computers centers.",
      applyUrl: "https://techmahindrafoundation.org/csr-grants"
    },
    {
      name: "National Primary Education Upliftment Fund",
      provider: "Ministry of Education (Samagra Shiksha)",
      type: "Government",
      sector: "Education",
      state: "National",
      minimumFunding: 1000000,
      maximumFunding: 5000000,
      deadline: "2026-12-31",
      eligibility: "National level NGOs registered on NGO Darpan, having audits for 5 preceding years.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, DARPAN Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Government incentive scheme targeting retention rate improvements in primary schools in rural blocks through teaching aid kits.",
      applyUrl: "https://education.gov.in/samagra-shiksha"
    },
    {
      name: "Tribal Children Scholarship Scheme",
      provider: "Azim Premji Foundation",
      type: "Foundation",
      sector: "Education",
      state: "Karnataka",
      minimumFunding: 300000,
      maximumFunding: 1500000,
      deadline: "2026-09-30",
      eligibility: "Active operations in aspirational districts of Karnataka. 12A exemption mandatory.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Provides financial aid and learning resources directly to tribal children and community learning centers.",
      applyUrl: "https://azimpremjifoundation.org/grants"
    },
    {
      name: "STEM Learning Support Program",
      provider: "Infosys Foundation (CSR)",
      type: "CSR",
      sector: "Education",
      state: "National",
      minimumFunding: 1500000,
      maximumFunding: 4000000,
      deadline: "2026-11-20",
      eligibility: "Registered NGO with dedicated STEM curriculum or lab capability, serving underfunded schools.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Audited Financial Statement",
      description: "Equipping schools with mini science centers, maths laboratories, and training modules for rural science teachers.",
      applyUrl: "https://www.infosys.com/infosys-foundation/grants"
    },
    {
      name: "Early Childhood Literacy Initiative",
      provider: "Tata Trusts",
      type: "Foundation",
      sector: "Education",
      state: "Maharashtra",
      minimumFunding: 800000,
      maximumFunding: 3000000,
      deadline: "2026-08-15",
      eligibility: "NGO registered under Bombay Public Trusts Act, active in early learning modules for urban slums.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Supporting Anganwadi learning updates, child assessment tools, and digital storybook libraries for slum communities.",
      applyUrl: "https://www.tatatrusts.org/our-grants"
    },
    {
      name: "Rural Primary Literacy Booster",
      provider: "Wipro Cares (CSR)",
      type: "CSR",
      sector: "Education",
      state: "Karnataka",
      minimumFunding: 400000,
      maximumFunding: 1500000,
      deadline: "2026-10-30",
      eligibility: "NGOs active in Karnataka primary government schools for at least 2 years.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Supports local tutoring boot camps, library building, and teachers learning kits for rural government schools.",
      applyUrl: "https://wiprofoundation.org/wipro-cares"
    },
    {
      name: "Girls High School Science Lab Grant",
      provider: "Cognizant Foundation",
      type: "Foundation",
      sector: "Education",
      state: "Tamil Nadu",
      minimumFunding: 600000,
      maximumFunding: 1800000,
      deadline: "2026-11-15",
      eligibility: "Registered NGOs focusing on girl child education and stem laboratories setup in Tamil Nadu.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Funding modern physics, chemistry, and biology laboratory equipment inside underfunded girls government high schools.",
      applyUrl: "https://www.cognizantfoundation.org"
    },
    {
      name: "Digital Literacy for Tribal Youth",
      provider: "Ministry of Tribal Affairs",
      type: "Government",
      sector: "Education",
      state: "National",
      minimumFunding: 1000000,
      maximumFunding: 3000000,
      deadline: "2027-01-31",
      eligibility: "Verified Darpan ID, active in tribal blocks with proper local administrative approvals.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, 12A Certificate, Audited Financial Statement",
      description: "Central government grant for establishing computer training kiosks and basic digital skills certifications in tribal belts.",
      applyUrl: "https://tribal.nic.in"
    },

    // --- HEALTHCARE ---
    {
      name: "Rural Maternal & Child Health Support Program",
      provider: "Reliance Foundation (CSR)",
      type: "CSR",
      sector: "Healthcare",
      state: "Maharashtra",
      minimumFunding: 1000000,
      maximumFunding: 3000000,
      deadline: "2026-09-10",
      eligibility: "Medical NGO or trust with dynamic local clinic capability in Maharashtra. 80G status verified.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Annual Activity Report",
      description: "Funding mobile clinic units, immunisation camps, and primary screening centers for rural mothers.",
      applyUrl: "https://www.reliancefoundation.org/healthcare"
    },
    {
      name: "National Mental Health Awareness Grant",
      provider: "Ministry of Health & Family Welfare",
      type: "Government",
      sector: "Healthcare",
      state: "National",
      minimumFunding: 2000000,
      maximumFunding: 6000000,
      deadline: "2027-01-15",
      eligibility: "Verified Darpan ID and 12A/80G filings. Expertise in clinical counselling or helplines.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Audited Financial Statement",
      description: "Central government assistance for localized mental health counselling centers, student stress helplines, and de-addiction clinics.",
      applyUrl: "https://main.mohfw.gov.in/grants"
    },
    {
      name: "Cancer Screening Mobile Camps Grant",
      provider: "Biocon Foundation",
      type: "Foundation",
      sector: "Healthcare",
      state: "Karnataka",
      minimumFunding: 500000,
      maximumFunding: 2500000,
      deadline: "2026-10-31",
      eligibility: "NGO partner with qualified medical volunteers and oncology screening tools operating in Karnataka.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Financial grant for hiring diagnostic buses, cancer screening kits, and rural patient navigation programs.",
      applyUrl: "https://www.bioconfoundation.org/grants"
    },
    {
      name: "Primary Eye Care Outreach Program",
      provider: "L&T Public Charitable Trust (CSR)",
      type: "CSR",
      sector: "Healthcare",
      state: "Gujarat",
      minimumFunding: 400000,
      maximumFunding: 1200000,
      deadline: "2026-11-15",
      eligibility: "Trust registration, operating for at least 3 years in Gujarat, focus on ophthalmology care.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding cataract surgery mobile units, diagnostic equipment, and free prescription glasses distributions.",
      applyUrl: "https://www.ltcharitabletrust.org"
    },
    {
      name: "Clean Water and Preventive Health Grant",
      provider: "Bill & Melinda Gates Foundation",
      type: "Foundation",
      sector: "Healthcare",
      state: "National",
      minimumFunding: 2500000,
      maximumFunding: 10000000,
      deadline: "2026-12-10",
      eligibility: "Established NGOs with deep local water security models and preventive health databases.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Scales low-cost filtration technology and community-level water sanitation training to control diarrheal diseases.",
      applyUrl: "https://www.gatesfoundation.org/grants"
    },
    {
      name: "Mobile Dental Clinic for Underprivileged Kids",
      provider: "Colgate-Palmolive CSR",
      type: "CSR",
      sector: "Healthcare",
      state: "Maharashtra",
      minimumFunding: 500000,
      maximumFunding: 1200000,
      deadline: "2026-09-25",
      eligibility: "Active NGOs working in public dental hygiene camps with medical license parameters in Maharashtra.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding mobile clinic vans equipped with dental chairs and basic dental treatment tools for underprivileged school kids.",
      applyUrl: "https://www.colgatepalmolive.co.in"
    },
    {
      name: "Arogya Bharat Community Health Grant",
      provider: "Ministry of Ayush",
      type: "Government",
      sector: "Healthcare",
      state: "National",
      minimumFunding: 1500000,
      maximumFunding: 4500000,
      deadline: "2026-11-20",
      eligibility: "Registered NGOs on Darpan, focusing on traditional wellness awareness and basic rural treatment infrastructure.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, 12A Certificate, Audited Financial Statement",
      description: "Government subsidy for establishing yoga centers and herbal therapy awareness wings in district hospitals.",
      applyUrl: "https://ayush.gov.in"
    },
    {
      name: "Pediatric Heart Surgery Support Program",
      provider: "Reliance Foundation",
      type: "Foundation",
      sector: "Healthcare",
      state: "National",
      minimumFunding: 2000000,
      maximumFunding: 6000000,
      deadline: "2026-12-30",
      eligibility: "National healthcare trusts linked with super-specialty child cardiac surgical clinics.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Supporting surgical expenses and medical costs for children from low-income families suffering from congenital heart defects.",
      applyUrl: "https://www.reliancefoundation.org"
    },

    // --- ENVIRONMENT ---
    {
      name: "Slum Solar Microgrid & Electrification Project",
      provider: "Tata Power Community Trust (CSR)",
      type: "CSR",
      sector: "Environment",
      state: "Maharashtra",
      minimumFunding: 600000,
      maximumFunding: 2200000,
      deadline: "2026-11-30",
      eligibility: "Registered NGO with clean energy credentials, operating in Maharashtra slum zones.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding installation of shared solar microgrids, community charging panels, and green energy workshops.",
      applyUrl: "https://www.tatapower.com/sustainability"
    },
    {
      name: "National Afforestation and Eco-Development Grant",
      provider: "Ministry of Environment, Forest & Climate Change",
      type: "Government",
      sector: "Environment",
      state: "National",
      minimumFunding: 1500000,
      maximumFunding: 5000000,
      deadline: "2027-02-28",
      eligibility: "NGOs with active land restoration credentials and government land partnership approvals.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, DARPAN Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Government funding under Green India Mission for large-scale afforestation, native saplings nurseries, and degraded forest land updates.",
      applyUrl: "https://moef.gov.in"
    },
    {
      name: "E-Waste Recycling & Slum Collection Fund",
      provider: "Wipro Foundation",
      type: "Foundation",
      sector: "Environment",
      state: "Karnataka",
      minimumFunding: 500000,
      maximumFunding: 1800000,
      deadline: "2026-09-15",
      eligibility: "NGO operating in urban waste models in Bengaluru with a valid recycling partner MOU.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Supports training informal waste collectors, setting up collection boxes, and safety protocols for electronic waste disposal.",
      applyUrl: "https://wiprofoundation.org/grants"
    },
    {
      name: "Water Conservation and Rainwater Harvesting Grant",
      provider: "ITC Limited (CSR)",
      type: "CSR",
      sector: "Environment",
      state: "Telangana",
      minimumFunding: 1000000,
      maximumFunding: 3500000,
      deadline: "2026-10-25",
      eligibility: "NGOs with agricultural sustainability and water storage structure design capacity in Telangana.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding check dams, desiltation of lakes, and domestic rainwater harvesting structures in drought-prone areas.",
      applyUrl: "https://www.itcportal.com/sustainability"
    },
    {
      name: "Slum Waste-to-Energy Community Program",
      provider: "Godrej Group (CSR)",
      type: "CSR",
      sector: "Environment",
      state: "Maharashtra",
      minimumFunding: 500000,
      maximumFunding: 1500000,
      deadline: "2026-08-30",
      eligibility: "NGO focused on solid waste, running composting or biogas pilot projects in Mumbai slums.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding dry waste segregation systems, biogas units for community kitchens, and plastic upcycling setups.",
      applyUrl: "https://www.godrej.com/sustainability"
    },
    {
      name: "Urban Miyawaki Forestation Grant",
      provider: "Godrej Properties (CSR)",
      type: "CSR",
      sector: "Environment",
      state: "National",
      minimumFunding: 800000,
      maximumFunding: 2000000,
      deadline: "2026-10-15",
      eligibility: "Active NGOs with expertise in afforestation and botanical systems using the Miyawaki technique.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding establishment of mini-forest reserves inside urban layout zones to offset industrial carbon footprints.",
      applyUrl: "https://www.godrejproperties.com/csr"
    },
    {
      name: "Community Lake Restoration & Rainwater Project",
      provider: "Wipro Foundation",
      type: "Foundation",
      sector: "Environment",
      state: "Karnataka",
      minimumFunding: 1000000,
      maximumFunding: 3000000,
      deadline: "2026-09-30",
      eligibility: "NGO registered in Karnataka with water security structures build experience.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Desilting local community lakes, setting up biological filters, and building rainwater harvesting wells for water recharge.",
      applyUrl: "https://wiprofoundation.org"
    },

    // --- WOMEN EMPOWERMENT ---
    {
      name: "Women Self-Help Group Livelihood Scale Grant",
      provider: "HDFC Bank (Parivartan CSR)",
      type: "CSR",
      sector: "Women Empowerment",
      state: "National",
      minimumFunding: 1200000,
      maximumFunding: 4500000,
      deadline: "2026-09-20",
      eligibility: "Registered NGOs with demonstrated capability in organizing SHGs and financial literacy training.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Audited Financial Statement",
      description: "Supports women micro-entrepreneurs with training in tailoring, organic farming, marketing, and business planning.",
      applyUrl: "https://www.hdfcbank.com/csr"
    },
    {
      name: "Mahila Shakti Kendra Assistance",
      provider: "Ministry of Women and Child Development",
      type: "Government",
      sector: "Women Empowerment",
      state: "National",
      minimumFunding: 2000000,
      maximumFunding: 8000000,
      deadline: "2026-11-30",
      eligibility: "Registered NGO on Darpan with 5+ years of verified women skill-development programs.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, DARPAN Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Government grant supporting rural women help-centers, legal advisory helplines, and basic healthcare awareness units.",
      applyUrl: "https://wcd.nic.in"
    },
    {
      name: "Slum Women Digital Literacy Initiative",
      provider: "Adobe Foundation",
      type: "Foundation",
      sector: "Women Empowerment",
      state: "Telangana",
      minimumFunding: 600000,
      maximumFunding: 2000000,
      deadline: "2026-10-10",
      eligibility: "Active NGO in Hyderabad slum areas, carrying out digital literacy or coding modules for girls.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Funding computer labs, basic accounting software training, and digital marketing modules for women micro-sellers.",
      applyUrl: "https://www.adobe.com/corporate-responsibility"
    },
    {
      name: "Preventing Gender-Based Violence Fund",
      provider: "Ford Foundation",
      type: "Foundation",
      sector: "Women Empowerment",
      state: "National",
      minimumFunding: 2500000,
      maximumFunding: 7500000,
      deadline: "2026-12-15",
      eligibility: "NGO active in human rights, female counseling, and community-led legal clinics.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Supports scaling local help booths, providing legal counsel to survivors, and gender sensitivity school campaigns.",
      applyUrl: "https://www.fordfoundation.org/work/our-grants"
    },
    {
      name: "Micro-Credit and Handicrafts Skill Fund",
      provider: "Fabindia Foundation",
      type: "Foundation",
      sector: "Women Empowerment",
      state: "Andhra Pradesh",
      minimumFunding: 300000,
      maximumFunding: 1000000,
      deadline: "2026-08-31",
      eligibility: "Registered Trust focusing on traditional handicrafts and weavers development in Andhra Pradesh.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Provides startup kits, looms, and raw materials to rural women artisans, enabling direct export supply links.",
      applyUrl: "https://www.fabindia.com/foundation"
    },
    {
      name: "Safe Transit & Hostel Support for Working Women",
      provider: "Aditya Birla Group (CSR)",
      type: "CSR",
      sector: "Women Empowerment",
      state: "Gujarat",
      minimumFunding: 1000000,
      maximumFunding: 2500000,
      deadline: "2026-10-10",
      eligibility: "Registered NGOs with hostel build approvals or transit arrangements in urban industrial blocks of Gujarat.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding construction of working women hostels, security facilities, and CCTV surveillance networks.",
      applyUrl: "https://www.adityabirla.com"
    },
    {
      name: "Mahila Udyami Loan & Skill Assistance",
      provider: "SIDBI Foundation",
      type: "Government",
      sector: "Women Empowerment",
      state: "National",
      minimumFunding: 2500000,
      maximumFunding: 7500000,
      deadline: "2026-12-15",
      eligibility: "Darpan verified registration, active in microfinance models or self-help group setups.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, 12A Certificate, Audited Financial Statement",
      description: "Subsidy for providing revolving funds and credit resources directly to rural mahila co-operatives.",
      applyUrl: "https://www.sidbi.in"
    },
    {
      name: "Single Mother Livelihood Rehabilitation",
      provider: "Deshpande Foundation",
      type: "Foundation",
      sector: "Women Empowerment",
      state: "Karnataka",
      minimumFunding: 400000,
      maximumFunding: 1500000,
      deadline: "2026-09-20",
      eligibility: "NGOs active in rehabilitation programs, having counselors and skill training units in Hubli/Belagavi.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Provides basic sewing machines, food processing gear, and business mentors to single mothers.",
      applyUrl: "https://www.deshpandefoundationindia.org"
    },

    // --- RURAL DEVELOPMENT ---
    {
      name: "Safe Water & Rural Sanitation Initiative",
      provider: "ICICI Foundation (CSR)",
      type: "CSR",
      sector: "Rural Development",
      state: "Telangana",
      minimumFunding: 800000,
      maximumFunding: 2500000,
      deadline: "2026-10-05",
      eligibility: "Operating in Telangana rural sectors with established water infrastructure validation history.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Annual Activity Report",
      description: "Funding installation of low-cost water purification kiosks, household toilets, and local sanitation awareness committees.",
      applyUrl: "https://www.icicifoundation.org"
    },
    {
      name: "Aspirational Districts Infrastructure Support",
      provider: "NITI Aayog (Gov Link)",
      type: "Government",
      sector: "Rural Development",
      state: "National",
      minimumFunding: 3000000,
      maximumFunding: 10000000,
      deadline: "2026-12-15",
      eligibility: "National level NGOs partner list, serving designated aspirational districts.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, DARPAN Certificate, Audited Financial Statement",
      description: "Central government funds for public utility construction, rural link roads, solar street lighting, and Anganwadis infrastructure.",
      applyUrl: "https://niti.gov.in"
    },
    {
      name: "Integrated Watershed and Farming Development",
      provider: "NABARD Rural Infrastructure Fund",
      type: "Government",
      sector: "Rural Development",
      state: "National",
      minimumFunding: 2000000,
      maximumFunding: 5000000,
      deadline: "2027-03-31",
      eligibility: "Darpan verified registration, active in agricultural or soil science projects.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, DARPAN Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Government support for constructing farm ponds, bunding, organic manure conversion, and drip irrigation lines.",
      applyUrl: "https://www.nabard.org"
    },
    {
      name: "Rural Off-Grid Solar Electrification Project",
      provider: "MacArthur Foundation",
      type: "Foundation",
      sector: "Rural Development",
      state: "National",
      minimumFunding: 2500000,
      maximumFunding: 9000000,
      deadline: "2026-11-15",
      eligibility: "NGO active in clean energy deployment, serving grid-remote tribal villages.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement",
      description: "Funding modular solar home systems, micro solar grids, and training local youths as repair technicians.",
      applyUrl: "https://www.macfound.org"
    },
    {
      name: "Solar Powered Drinking Water Purifiers for Villages",
      provider: "Adani Foundation (CSR)",
      type: "CSR",
      sector: "Rural Development",
      state: "Gujarat",
      minimumFunding: 1500000,
      maximumFunding: 4000000,
      deadline: "2026-11-20",
      eligibility: "NGOs operating water purification systems with solar energy compatibility in rural Gujarat.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Installs high-capacity solar reverse osmosis systems in salt-pan worker blocks and drought-prone villages.",
      applyUrl: "https://www.adanifoundation.org"
    },
    {
      name: "Village Sanitation & Household Toilets Scheme",
      provider: "Ministry of Drinking Water and Sanitation",
      type: "Government",
      sector: "Rural Development",
      state: "National",
      minimumFunding: 2000000,
      maximumFunding: 5000000,
      deadline: "2026-12-30",
      eligibility: "Darpan verified NGOs collaborating under Swachh Bharat Abhiyan rules in rural blocks.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, 12A Certificate, Audited Financial Statement",
      description: "Government incentive for construction of individual household latrines, community sanitary complexes, and liquid waste drains.",
      applyUrl: "https://jalshakti-ddws.gov.in"
    },

    // --- SKILL DEVELOPMENT ---
    {
      name: "Slum Youth Livelihoods & Skilling Program",
      provider: "Larsen & Toubro CSR",
      type: "CSR",
      sector: "Skill Development",
      state: "Telangana",
      minimumFunding: 1000000,
      maximumFunding: 3000000,
      deadline: "2026-11-10",
      eligibility: "NGO conducting vocational skill development in Hyderabad slum communities.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Annual Activity Report",
      description: "Funding youth computer centers, tailoring training institutes, and placement-linked skilling programs.",
      applyUrl: "https://www.larsentoubro.com/csr"
    },
    {
      name: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY) NGO Subgrant",
      provider: "National Skill Development Corporation (NSDC)",
      type: "Government",
      sector: "Skill Development",
      state: "National",
      minimumFunding: 1500000,
      maximumFunding: 6000000,
      deadline: "2026-10-31",
      eligibility: "NSDC-accredited training partners or NGOs having designated laboratory infrastructures.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, DARPAN Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Government funding under skill development mission, supporting free vocational certification training across diverse trades.",
      applyUrl: "https://www.pmkvyofficial.org"
    },
    {
      name: "Digital Literacy and Employability Initiative",
      provider: "Google.org",
      type: "Foundation",
      sector: "Skill Development",
      state: "National",
      minimumFunding: 3000000,
      maximumFunding: 10000000,
      deadline: "2026-12-05",
      eligibility: "NGOs with active digital literacy networks and job placement links for low-income youths.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement",
      description: "Funding computers infrastructure, internet subscriptions, localized skilling curriculum, and job fairs.",
      applyUrl: "https://google.org/grants"
    },
    {
      name: "Disable-Friendly Vocational Skilling",
      provider: "Kotak Mahindra Bank CSR",
      type: "CSR",
      sector: "Skill Development",
      state: "Maharashtra",
      minimumFunding: 800000,
      maximumFunding: 2500000,
      deadline: "2026-09-15",
      eligibility: "NGO specializing in rehabilitation or training for specially-abled youth in Maharashtra.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding adaptive computing laboratories, braille training materials, and placement link support.",
      applyUrl: "https://www.kotak.com/en/about-us/csr"
    },
    {
      name: "Green Collar Jobs Skilling Initiative",
      provider: "Schneider Electric (CSR)",
      type: "CSR",
      sector: "Skill Development",
      state: "National",
      minimumFunding: 1200000,
      maximumFunding: 3500000,
      deadline: "2026-11-10",
      eligibility: "Registered NGOs with electrical lab capacity or solar technician training resources.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Providing electrical training modules, micro-solar grid installation kits, and safety certifications for youth.",
      applyUrl: "https://www.se.com/in/en/about-us/sustainability"
    },
    {
      name: "NSDC Pradhan Mantri Kaushal Kendra Grant",
      provider: "Ministry of Skill Development & Entrepreneurship",
      type: "Government",
      sector: "Skill Development",
      state: "National",
      minimumFunding: 3000000,
      maximumFunding: 9000000,
      deadline: "2026-12-20",
      eligibility: "Accredited training centers with dedicated infrastructure for multiple vocational trades.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, 12A Certificate, Audited Financial Statement",
      description: "Government grant for scaling state-of-the-art training centers, offering vocational modules in healthcare, electronics, and automotive.",
      applyUrl: "https://www.msde.gov.in"
    },
    {
      name: "Women Tailoring and Fashion Design Academy",
      provider: "Sarla Devi Trust",
      type: "Foundation",
      sector: "Skill Development",
      state: "Rajasthan",
      minimumFunding: 500000,
      maximumFunding: 1500000,
      deadline: "2026-09-30",
      eligibility: "NGOs active in women self-employment initiatives in rural Rajasthan blocks.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Funding modern sewing machine centers, raw textile logistics, and fashion design trainers for village girls.",
      applyUrl: "https://sarladevitrust.org"
    },

    // --- ANIMAL WELFARE ---
    {
      name: "Stray Animal Mobile Clinic and Shelter Update",
      provider: "Maruti Suzuki CSR",
      type: "CSR",
      sector: "Animal Welfare",
      state: "National",
      minimumFunding: 400000,
      maximumFunding: 1500000,
      deadline: "2026-09-25",
      eligibility: "NGO with registered veterinary shelter and active local stray care vehicles.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding procurement of veterinary ambulance units, surgical kits, and stray animal cage updates.",
      applyUrl: "https://www.marutisuzuki.com/corporate/csr"
    },
    {
      name: "Animal Protection & Shelter Construction Grant",
      provider: "Wildlife Trust of India",
      type: "Foundation",
      sector: "Animal Welfare",
      state: "National",
      minimumFunding: 300000,
      maximumFunding: 1200000,
      deadline: "2026-10-15",
      eligibility: "NGO with dedicated stray shelter facility or emergency medical camp capacity.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report",
      description: "Funding building modifications, anti-rabies vaccination campaigns, and veterinary doctors compensation.",
      applyUrl: "https://www.wti.org.in"
    },
    {
      name: "Urban Stray Dog Vaccination & Sterilisation Camp",
      provider: "PepsiCo (CSR)",
      type: "CSR",
      sector: "Animal Welfare",
      state: "National",
      minimumFunding: 300000,
      maximumFunding: 800000,
      deadline: "2026-09-20",
      eligibility: "NGOs running veterinary shelter programs with AWBI (Animal Welfare Board of India) certification.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding anti-rabies vaccines, sterilisation equipment, and public awareness pamphlets in municipal blocks.",
      applyUrl: "https://www.pepsicoindia.co.in"
    },
    {
      name: "Endangered Bird Sanctuary Habitat Protection",
      provider: "WWF India Foundation",
      type: "Foundation",
      sector: "Animal Welfare",
      state: "Rajasthan",
      minimumFunding: 600000,
      maximumFunding: 1800000,
      deadline: "2026-10-20",
      eligibility: "Environmental or animal welfare NGOs with active trackers in wetland zones of Rajasthan.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Desilting local lakes, establishing tracking watchtowers, and hiring local community bird watchers.",
      applyUrl: "https://www.wwfindia.org"
    },
    {
      name: "Cattle Rescue and Veterinary Care Shelter",
      provider: "Dabur CSR",
      type: "CSR",
      sector: "Animal Welfare",
      state: "National",
      minimumFunding: 500000,
      maximumFunding: 1500000,
      deadline: "2026-11-15",
      eligibility: "AWBI-registered organizations with shelter facility and local fodder supply lines.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding veterinary care, cattle sheds reconstruction, vaccine programs, and fodder storage spaces.",
      applyUrl: "https://www.dabur.com"
    },
    {
      name: "Wildlife Rescue and Rehabilitation Grant",
      provider: "Born Free Foundation",
      type: "Foundation",
      sector: "Animal Welfare",
      state: "National",
      minimumFunding: 1000000,
      maximumFunding: 4000000,
      deadline: "2026-12-10",
      eligibility: "NGOs certified for wild animal handling, having qualified vets and response units.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement, Annual Activity Report",
      description: "Supports rescue operations, purchase of tranquilizer guns, transport cages, and primary diagnostic clinics.",
      applyUrl: "https://www.bornfree.org.uk"
    },

    // --- DISASTER RELIEF ---
    {
      name: "Emergency Flood Relief & Rehabilitation Kits",
      provider: "SBI Foundation (CSR)",
      type: "CSR",
      sector: "Disaster Relief",
      state: "National",
      minimumFunding: 1000000,
      maximumFunding: 5000000,
      deadline: "2026-08-31",
      eligibility: "Registered NGOs with verified disaster mitigation response team and regional storage centers.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate, Annual Activity Report",
      description: "Provides emergency dry food kits, temporary sanitation tents, medicines, and water purifying tables in disaster zones.",
      applyUrl: "https://www.sbifoundation.in"
    },
    {
      name: "Cyclone Emergency Shelter Construction Support",
      provider: "Oxfam India",
      type: "Foundation",
      sector: "Disaster Relief",
      state: "Andhra Pradesh",
      minimumFunding: 1500000,
      maximumFunding: 4000000,
      deadline: "2026-10-31",
      eligibility: "NGO operating in coastal blocks of Andhra Pradesh with disaster relief experience.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Audited Financial Statement",
      description: "Funding construction of multi-purpose cyclone shelters, rescue boats, and community training workshops.",
      applyUrl: "https://www.oxfamindia.org"
    },
    {
      name: "Coastal Cyclone Resilient Shelter Construction Support",
      provider: "Ministry of Home Affairs",
      type: "Government",
      sector: "Disaster Relief",
      state: "National",
      minimumFunding: 5000000,
      maximumFunding: 15000000,
      deadline: "2026-12-15",
      eligibility: "Darpan registered national level NGOs with civil engineering supervision capability in coastal areas.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, 12A Certificate, Audited Financial Statement",
      description: "Government scheme under NDRF for constructing cyclone-resistant shelters, solar backup lights, and fresh water storage reservoirs.",
      applyUrl: "https://www.mha.gov.in"
    },
    {
      name: "Emergency Medical Supplies Reserve Fund",
      provider: "Red Cross India Foundation",
      type: "Foundation",
      sector: "Disaster Relief",
      state: "National",
      minimumFunding: 1000000,
      maximumFunding: 3000000,
      deadline: "2026-11-20",
      eligibility: "Registered health trusts with disaster response credentials and emergency warehousing capacities.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, Annual Activity Report, Audited Financial Statement",
      description: "Provides emergency first-aid boxes, cholera vaccine kits, surgical tools, and field hospital logistics during disasters.",
      applyUrl: "https://www.indianredcross.org"
    },
    {
      name: "Community Earthquake Preparedness & Drills",
      provider: "NDMA (Government Link)",
      type: "Government",
      sector: "Disaster Relief",
      state: "National",
      minimumFunding: 800000,
      maximumFunding: 2500000,
      deadline: "2026-10-15",
      eligibility: "NGOs operating in seismic zone IV/V with disaster safety trainers on staff.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, DARPAN Certificate, Annual Activity Report",
      description: "Government funding for conducting mock earthquake drills, structural safety inspections, and building local rescue committees.",
      applyUrl: "https://ndma.gov.in"
    },
    {
      name: "Disaster Rehabilitation & Housing Grant",
      provider: "Ambuja Cements CSR",
      type: "CSR",
      sector: "Disaster Relief",
      state: "National",
      minimumFunding: 1200000,
      maximumFunding: 4500000,
      deadline: "2026-09-30",
      eligibility: "NGOs with low-cost housing models, construction engineers, and rehabilitation programs.",
      requiredDocuments: "Registration Certificate, PAN Card Copy, 12A Certificate, 80G Certificate, DARPAN Certificate",
      description: "Funding construction of brick-and-mortar homes for families displaced by earthquakes, landslides, or floods.",
      applyUrl: "https://www.ambujacement.com"
    }
  ];

  for (const g of grants) {
    await prisma.grant.create({ data: g });
  }

  console.log(`Successfully seeded ${grants.length} grants!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
