/**
 * Document type constants
 */

const DOCUMENT_TYPES = {
  REG_CERT: 'REG_CERT',
  PAN: 'PAN',
  TRUST_CERT_12A: 'TRUST_CERT_12A',
  TRUST_CERT_80G: 'TRUST_CERT_80G',
  ANNUAL_REPORT: 'ANNUAL_REPORT',
  FINANCIAL_REPORT: 'FINANCIAL_REPORT',
  DARPAN_CERT: 'DARPAN_CERT',
  PREV_PROPOSAL: 'PREV_PROPOSAL',
  PHOTO: 'PHOTO'
};

const REQUIRED_DOCUMENTS = [
  DOCUMENT_TYPES.REG_CERT,
  DOCUMENT_TYPES.PAN,
  DOCUMENT_TYPES.TRUST_CERT_12A
];

const DOCUMENT_LABELS = {
  [DOCUMENT_TYPES.REG_CERT]: 'Registration Certificate',
  [DOCUMENT_TYPES.PAN]: 'PAN Card Copy',
  [DOCUMENT_TYPES.TRUST_CERT_12A]: '12A Certificate',
  [DOCUMENT_TYPES.TRUST_CERT_80G]: '80G Certificate',
  [DOCUMENT_TYPES.ANNUAL_REPORT]: 'Annual Activity Report',
  [DOCUMENT_TYPES.FINANCIAL_REPORT]: 'Audited Financial Statement',
  [DOCUMENT_TYPES.DARPAN_CERT]: 'DARPAN Certificate',
  [DOCUMENT_TYPES.PREV_PROPOSAL]: 'Previous Grant Proposal',
  [DOCUMENT_TYPES.PHOTO]: 'NGO Photo'
};

module.exports = {
  DOCUMENT_TYPES,
  REQUIRED_DOCUMENTS,
  DOCUMENT_LABELS
};
