/**
 * NGO status constants
 */

const NGO_STATUS = {
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const USER_ROLES = {
  NGO: 'NGO',
  CITIZEN: 'CITIZEN',
  ORG: 'ORG',
  ADMIN: 'ADMIN'
};

const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  RESPONDED_INTERESTED: 'RESPONDED_INTERESTED',
  RESPONDED_DECLINED: 'RESPONDED_DECLINED',
  FUNDS_RECEIVED: 'FUNDS_RECEIVED'
};

const GRANT_TYPES = {
  CSR: 'CSR',
  GOVERNMENT: 'Government',
  FOUNDATION: 'Foundation'
};

module.exports = {
  NGO_STATUS,
  USER_ROLES,
  APPLICATION_STATUS,
  GRANT_TYPES
};
